### ISSUE TITLE
Estudar o uso da API

### ISSUE THREAD

**Issue by vct-h-dias** [vct-h-dias/IBGE-Insides#9]

**Comment by vct-h-dias** [comment]
Baixe o Insomnia, um gerenciador de request e explore como a API do IBGE funciona:

- [x] Estude o documento que disponibilizei no Drive

- [x] Baixe o Insomnia (disponivel na loja do Ubuntu, Ubuntu Software) 

- [x] Analisar as duas rotas e suas três querys (totalizando 6 tipos de requests diferentes)

Veja as Documentações da API: https://servicodados.ibge.gov.br/api/docs/nomes?versao=2

**Comment by MatheusCamargoGinebro** [comment]
Tarefa concluída. Ainda há algumas dúvidas, mas é só ir praticando.
